spring.application.name=CRUD_Mysql

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url = jdbc:mysql://localhost:3306/your_databaseName?createDatabaseIfNotExist=true
spring.datasource.username = your_username
spring.datasource.password = your_password
spring.datasource.diver-class-name =com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true

logging.level.org.springframework.security=DEBUG
